#A = int(2)
#B = int(3)
#C = int(5)
#print(A==B or C>A)

L1 = int(input("Digite o primeiro lado: "))
L2 = int(input("Digite o segundo lado: "))
L3 = int(input("Digite o terceiro lado: "))
TRI = (L1 < L2 + L3) and (L2 < L1 + L3) and (L3 < L1 + L2)
EQ = (L1 == L2) and (L2 == L3)
ES = (L1 != L2) and (L2 != L3) and (L1 != L3)
print("Pode formar um TRIANGULO? ", TRI)
print("O triangulo é EQUILATERO? ", EQ)
print("O triangulo é ESCALENO? ", ES)